# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  simpleapi:
    image: simpleapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 7001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
  simpleconsole:
    image: simpleconsole
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw