# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  simpleapi:
    image: simpleapi
    build:
      context: ./SimpleAPI
      dockerfile: ./Dockerfile
    ports:
      - 7000:7001
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
